books/urls.py
from django.urls import path

from .views import BookDetailView, BookListView, SearchResultsListView

app_name = "books"


urlpatterns = [
    path("", BookListView.as_view(), name="book_list"),
    path("<uuid:pk>/", BookDetailView.as_view(), name="book_detail"),
    path("search/", SearchResultsListView.as_view(), name="search_results"),
]

bookstore_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

from books.sitemaps import BookSitemap
from pages.sitemaps import StaticViewSitemap

sitemaps = {"books": BookSitemap, "static": StaticViewSitemap}


urlpatterns = [
    path("anything-but-admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("books/", include("books.urls")),
    path("orders/", include("orders.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("", include("pages.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

orders/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.OrderPageView.as_view(), name="orders"),
    path("charge/", views.charge, name="charge"),
]

pages/urls.py
from django.urls import path

from pages.views import AboutPageView, ContactPageView, FeedbackPageView, HomePageView

app_name = "pages"


urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
    path("contact/", ContactPageView.as_view(), name="contact"),
    path("feedback/", FeedbackPageView.as_view(), name="feedback"),
]

books/models.py
import uuid

from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class Book(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=500)
    description = models.TextField()
    author = models.CharField(max_length=500)
    price = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    cover = models.ImageField(upload_to="covers/", blank=True)
    link = models.URLField(
        verbose_name=_("Download Link"), blank=True, null=True, max_length=500
    )

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        permissions = [
            ("special_status", "Can read all books"),
        ]
        ordering = ("-created_on",)

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse("books:book_detail", args=[str(self.id)])


class Review(models.Model):
    author = models.ForeignKey(
        get_user_model(), related_name="author", on_delete=models.CASCADE
    )
    book = models.ForeignKey(Book, related_name="reviews", on_delete=models.CASCADE)
    review = models.CharField(max_length=255)

    def __str__(self):
        return self.review

orders/models.py
# Create your models here.

pages/models.py
# Create your models here.

users/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

pages/forms.py
import logging

from django import forms
from django.core.mail import send_mail

logger = logging.getLogger(__name__)


class ContactForm(forms.Form):
    name = forms.CharField(max_length=200)
    message = forms.CharField(max_length=600, widget=forms.Textarea)

    def send_mail(self):
        logger.info("sending message...")
        message = "From {0}\nMessage {1}".format(
            self.cleaned_data["name"], self.cleaned_data["message"]
        )
        send_mail(
            subject="Site message",
            message=message,
            from_email="site@domain.con",
            recipient_list=["gurupratap.matharu@gmail.com"],
            fail_silently=False,
        )


class FeedbackForm(forms.Form):
    name = forms.CharField(max_length=200)
    message = forms.CharField(max_length=600, widget=forms.Textarea)

    def send_mail(self):
        logger.info("sending feedback...")
        message = "From {0}\nMessage {1}".format(
            self.cleaned_data["name"], self.cleaned_data["message"]
        )
        send_mail(
            subject="Feedback message",
            message=message,
            from_email="site@domain.com",
            recipient_list=["gurupratap.matharu@gmail.com"],
            fail_silently=False,
        )

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "email",
            "username",
        )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "email",
            "username",
        )

books/views.py
from django.db.models import Q
from django.views.generic import DetailView, ListView

from .models import Book


class BookListView(ListView):
    model = Book
    context_object_name = "book_list"
    template_name = "books/book_list.html"
    paginate_by = 9


class BookDetailView(DetailView):
    model = Book
    context_object_name = "book"
    template_name = "books/book_detail.html"


class SearchResultsListView(ListView):
    model = Book
    context_object_name = "book_list"
    template_name = "books/search_results.html"

    def get_queryset(self):
        query = self.request.GET.get("q")
        return Book.objects.filter(
            Q(title__icontains=query) | Q(title__icontains=query)
        )

orders/views.py
from django.conf import settings
from django.contrib.auth.models import Permission
from django.shortcuts import render
from django.views.generic import TemplateView

import stripe

stripe.api_key = settings.STRIPE_TEST_SECRET_KEY


class OrderPageView(TemplateView):
    template_name = "orders/purchase.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["stripe_key"] = settings.STRIPE_TEST_PUBLISHABLE_KEY
        return context


def charge(request):
    permission = Permission.objects.get(codename="special_status")
    u = request.user
    u.user_permissions.add(permission)

    if request.method == "POST":
        stripe.Charge.create(
            amount=3900,
            currency="usd",
            description="Purchase all books",
            source=request.POST["stripeToken"],
        )
        return render(request, "orders/charge.html")

pages/views.py
import logging

from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import FormView, TemplateView

from pages.forms import ContactForm, FeedbackForm

logger = logging.getLogger(__name__)


class HomePageView(TemplateView):
    template_name = "home.html"


class AboutPageView(TemplateView):
    template_name = "about.html"


class ContactPageView(SuccessMessageMixin, FormView):
    form_class = ContactForm
    template_name = "pages/contact.html"
    success_url = "/"
    success_message = "Message sent successfully!"

    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)


class FeedbackPageView(SuccessMessageMixin, FormView):
    form_class = FeedbackForm
    template_name = "pages/feedback.html"
    success_url = "/"
    success_message = "Feedback sent successfully!"

    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)

pages/templates/pages/contact.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block title %}
  Contact | Bookstore
{% endblock title %}

{% block content %}
  <div class="card border-0">
    <div class="card-header bg-white border-light">
      <h3>Contact</h3>
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="d-flex justify-content-end mt-3">
          <a href="{% url 'pages:home' %}" class="btn btn-light me-3">Cancel</a>
          <button type="submit" class="btn btn-success">Send</button>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

pages/templates/pages/feedback.html
{% extends "_base.html" %}

{% load crispy_forms_tags %}

{% block title %}
  Feedback | Bookstore
{% endblock title %}

{% block content %}
  <div class="card border-0">
    <div class="card-header bg-white border-0">
      <h3>Feedback</h3>
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="d-flex justify-content-end mt-3">
          <a href="{% url 'pages:home' %}" class="btn btn-light me-3">Cancel</a>
          <button type="submit" class="btn btn-success">Send</button>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

templates/_base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>

      {% block title %}
        Bookstore
      {% endblock title %}

    </title>
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/icons/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/icons/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/icons/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'assets/icons/favicon/site.webmanifest' %}">
    <!-- CSS -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link href="{% static 'assets/css/bootstrap.min.css' %}"
          rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
          crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'assets/css/autoComplete.min.css' %}">
    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/546230838a.js" crossorigin="anonymous"></script>
  </head>
  <body>

    {% include "_header.html" %}
    {% include "includes/_alert.html" %}

    <div class="container">
      <main class="min-vh-100">

        {% block content %}
        {% endblock content %}

      </main>

      {% include "includes/_footer.html" %}

    </div>
    <!-- JavaScript -->
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous">
    </script>
    <script src="{% static 'assets/js/htmx/htmx.min.js' %}"></script>
    <script src="{% static 'assets/js/htmx-main.js' %}"></script>
    <script src="{% static 'assets/js/autoComplete.min.js' %}"></script>
    <script src="{% static 'assets/js/autoComplete-main.js' %}"></script>
  </body>
</html>

templates/_header.html
<header>
  <nav class="navbar navbar-expand-lg"
       aria-label="Offcanvas navbar large">
    <div class="container-fluid">
      <a class="navbar-brand"
         href="{% url 'pages:home' %}">Bookstore</a>
      <button class="navbar-toggler"
              type="button"
              data-bs-toggle="offcanvas"
              data-bs-target="#offcanvasNavbar2"
              aria-controls="offcanvasNavbar2"
              aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end"
           tabindex="-1"
           id="offcanvasNavbar2"
           aria-labelledby="offcanvasNavbar2Label">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title"
              id="offcanvasNavbar2Label">Bookstore</h5>
          <button type="button"
                  class="btn-close btn-close-dark"
                  data-bs-dismiss="offcanvas"
                  aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <a class="nav-link"
                 href="{% url 'books:book_list' %}">Books</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle"
                 href="#"
                 role="button"
                 data-bs-toggle="dropdown"
                 aria-expanded="false">Profile</a>
              <ul class="dropdown-menu">
                {% if user.is_authenticated %}
                  <li>
                    <a class="dropdown-item"
                       href="{% url 'account_logout' %}">Logout</a>
                  </li>
                {% else %}
                  <li>
                    <a class="dropdown-item"
                       href="{% url 'account_login' %}">Login</a>
                  </li>
                  <li>
                    <a class="dropdown-item"
                       href="{% url 'account_signup' %}">Signup</a>
                  </li>
                {% endif %}
              </ul>
            </li>
          </ul>
          <form class="d-flex mt-3 mt-lg-0"
                role="search">
            <input class="form-control me-2"
                   type="search"
                   placeholder="Search"
                   aria-label="Search">
            <button class="btn btn-outline-success"
                    type="submit">Search</button>
          </form>
        </div>
      </div>
    </div>
  </nav>
</header>

templates/_toast.html
<div aria-live="polite" aria-atomic="true" style="position: relative; min-height: 1px;">
    <!-- Position it -->
    <div style="position: absolute; top: 0; right: 20px; min-width: 250px;">
        <!-- Then put toasts within -->
        {% if messages %}
        {% for message in messages %}
        <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-delay=5000>
            <div class="toast-header">
                <i class="fas fa-boxes"></i>
                <strong class="mr-auto ml-3">Message</strong>
                <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="toast-body">
                {{ message }}
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
</div>

templates/about.html
{% extends '_base.html' %}

{% block title %}About{% endblock title %}

{% block content %}
<h1>About Page</h1>
{% endblock content %}

templates/books/book_detail.html
{% extends "_base.html" %}

{% load static %}

{% block title %}
  {{ book.title }} | Bookstore
{% endblock title %}

{% block content %}
  <div class="card mt-3">
    <div class="card-header">Featured</div>
    <div class="card-body">
      <h5 class="card-title">{{ book.title }}</h5>
      <p class="card-text">{{ book.description }}</p>
      <a href="{{ book.link }}" class="btn btn-primary" target="_blank">Download</a>
    </div>
  </div>
{% endblock content %}

templates/books/book_list.html
{% extends "_base.html" %}

{% block title %}
  Books
{% endblock title %}

{% block content %}
  <div class="album py-5">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for book in book_list %}
          <div class="col">
            <div class="card h-100 shadow-sm">
              <div class="card-body">
                <h6 class="card-title">{{ book.title|truncatechars:100 }}</h6>
                {% comment "Tip" %}Use the subtitle below for tags|authors|keywords{% endcomment %}
                {% comment %} <p class="card-subtitle mb-2 text-body-secondary">Card subtitle</p> {% endcomment %}
                <p class="card-text">{{ book.description|truncatechars:120 }}</p>
              </div>
              <div class="card-footer bg-white d-flex justify-content-between">
                <small class="text-body-secondary mt-1">{{ book.created_on }}</small>
                <a type="button" href="{{ book.get_absolute_url }}" class="btn btn-sm btn-outline-primary">View</a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>

  {% include "includes/_pagination.html" %}

{% endblock content %}

templates/books/search_results.html
{% extends '_base.html' %}

{% block title %}
  Search
{% endblock title %}

{% block content %}
  <h1>Search Results</h1>
  {% for book in book_list %}
    <div>
      <h3>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
      </h3>
      <p class="text-muted">{{ book.author }}</p>
    </div>
  {% endfor %}
{% endblock content %}

templates/home.html
{% extends '_base.html' %}

{% load static %}

{% load socialaccount %}

{% block title %}
  Home
{% endblock title %}

{% block content %}
  <div>
    <div class="d-flex justify-content-center">
      <h1>Bookstore</h1>
    </div>
    <form method="get" action="{% url 'books:search_results' %}">
      <div class="d-flex justify-content-center">
        <input id="autoComplete"
               name="q"
               type="search"
               dir="ltr"
               spellcheck="false"
               autocorrect="off"
               autocomplete="off"
               autocapitalize="off"
               autofocus="autofocus"
               maxlength="2048"
               tabindex="1"
               aria-label="Search">
      </div>
    </form>
  </div>
{% endblock content %}

templates/includes/_alert.html
{% comment "Alert Icons" %}

Here we create a local SVG sprite like so to easily reference the same icons repeatedly.
in our alerts. We use the id of each SVG to our alert class (info, success, warning)
so that the correct svg is referenced in the alert.

For more details refer to https://getbootstrap.com/docs/5.0/components/alerts/

{% endcomment %}
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="success" fill="currentColor" viewBox="0 0 16 16">
  <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
  </symbol>
  <symbol id="info" fill="currentColor" viewBox="0 0 16 16">
  <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z" />
  </symbol>
  <symbol id="warning" fill="currentColor" viewBox="0 0 16 16">
  <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
  </symbol>
</svg>
{% if messages %}
  {% for message in messages %}
    {% with klass=message.tags %}
      <div class="alert alert-{{ klass }} d-flex align-items-center alert-dismissible fade show" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Info:">
          <use xlink:href="#{{ klass }}" />
        </svg>
        <span class="alert-text">{{ message }}</span>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endwith %}
  {% endfor %}
{% endif %}

templates/includes/_footer.html
<div class="container">
  <footer>
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item">
        <a href="{% url 'pages:home' %}" class="nav-link px-2 text-body-secondary">Home</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'pages:contact' %}" class="nav-link px-2 text-body-secondary">Contact</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'pages:feedback' %}" class="nav-link px-2 text-body-secondary">Feedback</a>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link px-2 text-body-secondary">FAQs</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'pages:about' %}" class="nav-link px-2 text-body-secondary">About</a>
      </li>
    </ul>
    <p class="text-center text-body-secondary">&copy; 2023 Bookstore, Inc</p>
  </footer>
</div>

templates/includes/_pagination.html
<!-- Paginator -->
<nav aria-label="Page navigation" class="py-md-5">
  <ul class="pagination pagination-separate justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page=1" aria-label="First">
          <span aria-hidden="true">First</span>
          <span class="sr-only">First</span>
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">{{ page_obj.previous_page_number }}</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">
        {{ page_obj.number }}
        <span class="sr-only">(current)</span>
      </span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">{{ page_obj.next_page_number }}</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
          <span aria-hidden="true">Last</span>
          <span class="sr-only">Last</span>
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
<!-- End Paginator -->

templates/orders/charge.html
{% extends '_base.html' %}

{% block title %}Charge{% endblock title %}

{% block content %}
<h2>Thank you for your order! You now have access to
    <a href="{% url 'book_list' %}">All Books</a></h2>
</h2>

{% endblock content %}

templates/orders/purchase.html
{% extends '_base.html' %}

{% block title %}Orders{% endblock title %}

{% block content %}

<h1>Orders Page</h1>
<p>Buy for $39.00</p>
<form action="{% url 'charge' %}" method="POST">
    {% csrf_token %}
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="{{ stripe_key }}"
        data-description="All Books" data-amount="3900" data-locale="auto"></script>
</form>

{% endblock content %}